### ISSUE TITLE
UI/UX Designer and Front-End developer

### ISSUE THREAD

**Issue by thiagotomasi** [projectbuendia/projectbuendia.github.io#3]
Hi,

I'm a Brazilian designer and front-end developer, and I really want to help in this project.
I have 7 year of experience, here is my LinkedIn profile: https://br.linkedin.com/in/thiagotomasi

I really want to help, let me know how.

Thanks very much,

PS.: Sorry to use the issues to get in contact, but the e-mail `buendia-dev@googlegroups.com` dosen't work

**Comment by vicainelli** [comment]
Hey @thiagotomasi, I created a proposal for a new design for the site, what do you think?

![http://i.imgur.com/KliH6OX.jpg](http://i.imgur.com/KliH6OX.jpg)
